export const AHORCADO_AUDIO: Record<string, any> = {
  "Mando polla gorda": require("../assets/audio/ahorcado/mandopolla gorda.wav"),
  "Soy de mando": require("../assets/audio/ahorcado/mandopolla gorda.wav"),
  "Soy humilde solo gano": require("../assets/audio/ahorcado/soy humilde solo gano.wav"),
  "Vamos cogerme los pezones y estirarlos": require("../assets/audio/ahorcado/cogerme los pezones y estirarlos.wav"),
  "Mirame la cobra": require("../assets/audio/ahorcado/mirame la cobra.wav"),
  "Blacklist es la mejor": require("../assets/audio/ahorcado/Blacklist es la mejor.wav"),
  "Ai se eu chi pego": require("../assets/audio/ahorcado/ai se eu chi pego.wav"),
  "Tu bebecito": require("../assets/audio/ahorcado/tu bebecito.wav"),
  "Glogloglo cometelo todo": require("../assets/audio/ahorcado/glogloglo cometelo todo.wav"),
  "Bueno basta ya": require("../assets/audio/ahorcado/bueno basta ya.wav"),
  "Que putada dios santo bendito por que": require("../assets/audio/ahorcado/que putada dios santo bendito por que.wav"),
  "La he cagado la ceo cagada": require("../assets/audio/ahorcado/la he cagado la ceo cagada.wav"),
  "Te gusta bien duro a a, yo soy la de tu autoescuela esa la de tu esquela a que no te fijabas en mi a a ahora ya te fijas a y ahora yo te digo tra tra": require("../assets/audio/ahorcado/te gusta bien duro a a (regueaton).wav"),
  "Toma toma toma": require("../assets/audio/ahorcado/toma toma toma.wav"),
  "Comerme to el pomelo": require("../assets/audio/ahorcado/comerme to el pomelo vamos.wav"),
  "Como tiene la porongda de chunga y dunga": require("../assets/audio/ahorcado/como tiene la poronga de chunga y dunga.wav"),
  "Aparte de esto gracias a dios": require("../assets/audio/ahorcado/aparte de esto gracias a dios.wav"),
  "Vamos mancos": require("../assets/audio/ahorcado/vamos mancos.wav"),
  "Lo que me pueden comer todos aqui": require("../assets/audio/ahorcado/lo que me pueden comer todos aqui.wav"),
  "Pero porque no se levanta el doraemon este": require("../assets/audio/ahorcado/pero porque no se levanta el doraemon este.wav"),
  "Nooooglogloglo que putada": require("../assets/audio/ahorcado/nooooglogloglo que putada.wav"),
  "La he cagado": require("../assets/audio/ahorcado/la he cagado.wav"),
  "Nunca es tarde para comerse un buen culo": require("../assets/audio/ahorcado/nunca es tarde para comerse un buen culo.wav"),
  "Papii perroo": require("../assets/audio/ahorcado/papii perroo.wav"),
  "Por el amor de esa mujer": require("../assets/audio/ahorcado/por el amor de esa mujer.wav"),
  "Noo la puta bala": require("../assets/audio/ahorcado/noo la puta balaa.wav"),
  "Que haces eres tonto": require("../assets/audio/ahorcado/que haces eres tonto.wav"),
  "Kerry Caberga": require("../assets/audio/ahorcado/kerry caberga.wav"),
  "Cabron quitate": require("../assets/audio/ahorcado/cabron quitate.wav"),
  "La Ceocague muy duro": require("../assets/audio/ahorcado/la ceocague muy duro.wav"),
  "Se puede ser mas torpe": require("../assets/audio/ahorcado/se puede ser mas torpe.wav"),
  "Puto panceta": require("../assets/audio/ahorcado/puto panceta.wav"),
  "El ceo acesino vuelve a vuestras casas": require("../assets/audio/ahorcado/el ceo asesino vuelve a vuestras casas.wav"),
  "Hijo de perra": require("../assets/audio/ahorcado/hijo de perra.wav"),
  "Cabeza moco ese hijo de la gran putin": require("../assets/audio/ahorcado/cabeza moco ese hijo de la gran putin.wav"),
  "Panceta panceta panceta panceta": require("../assets/audio/ahorcado/panceta panceta panceta panceta.wav"),
  "Quitate de ahi pedazo de cono": require("../assets/audio/ahorcado/quitate de ahi pedazo de cono.wav"),
  "Chau chau maravillau": require("../assets/audio/ahorcado/chau chau maravillau.wav"),
  "Robo total de verdad que verguenza": require("../assets/audio/ahorcado/robo total de verdad que verguenza.wav"),
};

export const getAhorcadoAudio = (phrase: string): any | null => AHORCADO_AUDIO[phrase] ?? null;
